#!/bin/zsh
#
# Create IDE.

#------------------------------------------------------------------------------
# Constants
#------------------------------------------------------------------------------
SRP_NAME=$(basename "$0")
REQS=(tmux vim)

#------------------------------------------------------------------------------
# Check if all required commands exist
#------------------------------------------------------------------------------
has_reqs=true
for req in "${REQS[@]}"; do
  type "${req}" &>/dev/null || has_reqs=false && break
done

if [[ ${has_reqs} == false ]]; then
  echo "${SRP_NAME}: required: ${REQS[*]}" 1>&2
  exit 1
fi

#------------------------------------------------------------------------------
# Validate arguments
#------------------------------------------------------------------------------
if (( $# > 1 )); then
  echo "usage: ${SRP_NAME} [directory]" 1>&2
  exit 1
fi

DIR=.
[[ -n $1 ]] && DIR=$1

if [[ ! -d ${DIR} ]]; then
  echo "${SRP_NAME}: ${DIR}: No such directory" 1>&2
  exit 1
fi

#------------------------------------------------------------------------------
# Main scripts
#------------------------------------------------------------------------------
if [[ -z ${TMUX} ]]; then
  tmux new-session -d
  tmux send-keys "${SRP_NAME} ${DIR}" Enter
  tmux attach-session
fi

if (( $(tmux list-panes | wc -l) >= 2 )); then
  echo "${SRP_NAME}: Current window is already splited" 1>&2
  exit 1
fi

tmux send-keys "cd ${DIR}"                  Enter
tmux send-keys "tmux split-window -d -l 16" Enter C-l
tmux send-keys 'vim .'                      Enter
